language: java
dist: xenial
os: linux
jdk: oraclejdk11

addons:
  apt:
    packages:
      - lynx

services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

script:
  - cp build/environment/environment.properties.example build/environment/environment.properties
  - cp build/environment/testEnvironment.json.example build/environment/testEnvironment.json
  - docker-compose -f docker-compose.unittest.yml up -d --build
  - docker ps
  - docker exec runner-chrome mvn checkstyle:check
  - mvn checkstyle:check
  - docker exec runner-chrome mvn compile test -Dcucumber.filter.tags="@applydbmigrations"
  - docker exec runner-chrome mvn compile test -Dcucumber.filter.tags="@UnitTest" || echo "done"
  - docker exec runner-chrome mvn io.qameta.allure:allure-maven:report
  - cd runner-results
  - ls -la

before_deploy:
  - cp runner-results/extent-results/SparkReport/Spark.html runner-results/extent-results/SparkReport/index.html

deploy:
  local_dir: runner-results/extent-results/SparkReport
  provider: pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    all_branches: true

after_deploy:
  - docker-compose -f docker-compose.unittest.yml down